version: '3.7'

services:
  postgres:
    build: "./database"
    
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - "discovery.type=single-node"